In [1]:
import pandas as pd
import matplotlib.pylab as plt

In [2]:
data= {
    "Tracation_ID":[1,2,3,4,5],
    "Item_Purchased":[["bread","milk"],["bread","milk","butter"],["bread","butter"],["milk","butter"],["bread","milk","butter"]]
}

In [5]:
df=pd.DataFrame(data)
df

   Tracation_ID         Item_Purchased
0             1          [bread, milk]
1             2  [bread, milk, butter]
2             3        [bread, butter]
3             4         [milk, butter]
4             5  [bread, milk, butter]

To Solve Asscoiation Algorithm we want to calclute 
i)Frequrnt Items Set
ii) Association rule genration

Now as we see then the one column is in text or string formate so 
we want to use encoder to encoder it but note but to it's is tracation dataset 
we want work with python (mixtend) libery import TaanscationEncode

In [9]:
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
df_encode=te.fit_transform(df["Item_Purchased"])
df_encode

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [11]:
#convert into DataFrame
df_encode=pd.DataFrame(df_encode,columns=te.columns_)
df_encode

   bread  butter   milk
0   True   False   True
1   True    True   True
2   True    True  False
3  False    True   True
4   True    True   True

#Now impoert mlxtren Librery

In [12]:
from mlxtend.frequent_patterns import association_rules,apriori

In [13]:
frq_item_set=apriori(df_encode,min_support=0.4,use_colnames=True)

In [14]:
rules=association_rules(frq_item_set,min_threshold=0.6)

In [15]:
frq_item_set

   support                          itemsets
0      0.8                frozenset({bread})
1      0.8               frozenset({butter})
2      0.8                 frozenset({milk})
3      0.6        frozenset({bread, butter})
4      0.6          frozenset({bread, milk})
5      0.6         frozenset({milk, butter})
6      0.4  frozenset({bread, milk, butter})

In [16]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({bread}),frozenset({butter}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.6,-0.250000,0.750000
1,frozenset({butter}),frozenset({bread}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.6,-0.250000,0.750000
2,frozenset({bread}),frozenset({milk}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.6,-0.250000,0.750000
3,frozenset({milk}),frozenset({bread}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.6,-0.250000,0.750000
4,frozenset({milk}),frozenset({butter}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.6,-0.250000,0.750000
5,frozenset({butter}),frozenset({milk}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.6,-0.250000,0.750000
6,"frozenset({bread, milk})",frozenset({butter}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.4,-0.666667,0.583333
7,"frozenset({bread, butter})",frozenset({milk}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.4,-0.666667,0.583333
8,"frozenset({milk, butter})",frozenset({bread}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.4,-0.666667,0.583333